-- create tables
CREATE TABLE department (
    dept_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name      VARCHAR2(100) NOT NULL,
    location  VARCHAR2(100)
);

CREATE TABLE employee (
    emp_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    emp_name   VARCHAR2(100) NOT NULL,
    hire_date  DATE DEFAULT SYSDATE,
    salary     NUMBER(12,2),
    dept_id    NUMBER,
    CONSTRAINT fk_emp_dept FOREIGN KEY (dept_id) REFERENCES department(dept_id)
);

-- sample index
CREATE INDEX idx_emp_name ON employee(emp_name);

-- sample data
INSERT INTO department (name, location) VALUES ('IT', 'Bangalore');
INSERT INTO department (name, location) VALUES ('HR', 'Mumbai');
INSERT INTO department (name, location) VALUES ('SALES', 'Kolkata');

INSERT INTO employee (emp_name, salary, dept_id) VALUES ('Alice', 70000, 1);
INSERT INTO employee (emp_name, salary, dept_id) VALUES ('Bob', 50000, 1);
INSERT INTO employee (emp_name, salary, dept_id) VALUES ('Charlie', 45000, 2);
COMMIT;
